### ISSUE TITLE
Problem with fresh install

### ISSUE THREAD

**Issue by pedrommone** [alexnoz/webpack-pug-scss-boilerplate#3]
```
➜  harper git:(feature/boostrap) ✗ npm run start

> webpack-pug-scss-boiperplate@1.0.5 start /Users/pedromaia/Code/Ez/harper
> nodemon --watch webpack.config.js --exec "webpack-dev-server --open --hot --env development"

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: webpack.config.js
[nodemon] starting `webpack-dev-server --open --hot --env development`
/Users/pedromaia/Code/Ez/harper/webpack.parts.js:67
  parts.loadPug(),
        ^

TypeError: parts.loadPug is not a function
    at Object.<anonymous> (/Users/pedromaia/Code/Ez/harper/webpack.parts.js:67:9)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/pedromaia/Code/Ez/harper/webpack.config.js:13:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by alexnoz** [comment]
Sorry, I cannot reproduce this. Have you made any changes to `webpack.parts.js`? Btw, `npm run start` is redundant, you can just run `npm start` instead.

**Comment by alexnoz** [comment]
I'll close this, since there is no activity. Feel free to reopen if the issue persists.
