### ISSUE TITLE
After installing the modules, i did run, $ npm start . I got this error. I am on Linux Fedora 28, Node version v10.12.0

### ISSUE THREAD

**Issue by jankoboz** [alexnoz/webpack-pug-scss-boilerplate#9]
> nodemon --watch webpack.config.js --exec "webpack-dev-server --open --hot --env development"

[nodemon] 1.18.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: webpack.config.js
[nodemon] starting `webpack-dev-server --open --hot --env development`
/home/ciboz/Documents/projects/blog-website/__deneme__/webpack-pug-scss-boilerplate/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/ciboz/Documents/projects/blog-website/__deneme__/webpack-pug-scss-boilerplate/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at Object.<anonymous> (/home/ciboz/Documents/projects/blog-website/__deneme__/webpack-pug-scss-boilerplate/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by sp3ber** [comment]
Try to fix versions of
    "webpack": "4.8.3",
    "webpack-dev-server": "3.1.4"
(remove "^" prefix in package.json) or use yarn to install boilerplate (there are yarn.lock)
It helped me.

**Comment by jankoboz** [comment]
Perfect.  Worked for me. Thanks a lot
